#ifndef CASINO_HPP
#define CASINO_HPP

#include <vector>
#include <string>
#include <map>
#include "Game.hpp"
#include "Player.hpp"
#include "PlayerStats.hpp"

class Casino {
private:
    std::vector<Game*> games;         // Games available in the casino
    std::vector<Player*> players;     // Players registered in the casino
    double houseBalance;              // Casino's total balance

protected:
    // Calculates revenue generated by the casino
    double calculateRevenue();

public:
    // Constructor
    Casino();

    // Adds a new player to the casino
    void addPlayer(Player* player);

    // Removes a player by their ID, returns true if successful
    bool removePlayer(int playerId);

    // Returns a list of games in the casino
    std::vector<Game*> getGameList() const;

    // Getter for house balance
    double getHouseBalance() const;

    // Destructor
    ~Casino();
};

#endif // CASINO_HPP
